apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 72.4.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 8h0m0s
  install:
    createNamespace: true
  targetNamespace: monitoring
  values:
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - alertmanager.stag.devkuban.com
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - prometheus.stag.devkuban.com
      prometheusSpec:
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}

    # Add a simple test PrometheusRule that will create a PrometheusRule named
    # `test-alerts` in the monitoring namespace. The alert `TestAlert` uses
    # `vector(1)` and will be active immediately — useful for validating the
    # alerting pipeline (prometheus -> alertmanager -> receivers).
    additionalPrometheusRulesMap:
      test-alerts:
        groups:
          - name: test.rules
            rules:
              - alert: TestAlert
                expr: vector(1)
                labels:
                  severity: warning
                annotations:
                  summary: "Test alert from kube-prometheus-stack"
                  description: "This alert is generated to validate alert delivery and rules provisioning."

    grafana:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: nginx
          # nginx.ingress.kubernetes.io/ssl-redirect: "true"
        hosts:
          - grafana.stag.devkuban.com
        # tls:
        #   - secretName: wildcard-stag-devkuban-com-tls
        #     hosts:
        #       - grafana.stag.devkuban.com
    