apiVersion: v1
kind: Pod
metadata:
  name: nginx-podsthird
  labels:
    app: nginx
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
